# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contract_integrate'),
        ('authentications', '0002_auto_20180212_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrate',
            name='ci_from',
        ),
        migrations.RemoveField(
            model_name='integrate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Integrate',
        ),
    ]
