# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 09:19
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_auto_20180830_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='etc_entrypted_text_1',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='etc_entrypted_text_2',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='etc_entrypted_text_3',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
