# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def set_default_topic_list(apps, schema_editor):
    Topic = apps.get_model('notifications', 'topic')

    topics = settings.NOTIFICATIONS_SETTINGS.get('DEFAULT_TOPICS', [])

    for topic in topics:
        row = Topic(name=topic, description=topic)
        row.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, help_text='Inactive devices will not be sent notifications', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('application_id', models.CharField(blank=True, help_text='Opaque application identity, should be filled in for multiple key/certificate access', max_length=64, null=True, verbose_name='Application ID')),
                ('registration_id', models.TextField(verbose_name='Registration ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('protocol', models.CharField(choices=[('2', 'Email'), ('3', 'Push'), ('1', 'Sms')], help_text='전송 방법', max_length=1)),
                ('title', models.CharField(blank=True, help_text='알림 제목', max_length=128, null=True)),
                ('message', models.TextField(blank=True, help_text='알림 내용')),
                ('status', models.BooleanField(default=True, help_text='전송 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('register', models.ForeignKey(help_text='등록자', on_delete=django.db.models.deletion.CASCADE, related_name='notification_register', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('2', 'Email'), ('3', 'Push'), ('1', 'Sms')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='주제 명', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, help_text='주제에 대한 설명', max_length=64, null=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='subscribe',
            name='topics',
            field=models.ManyToManyField(to='notifications.Topic'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.ForeignKey(help_text='전송 주제', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.Topic'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='수신자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together=set([('user', 'type')]),
        ),
        migrations.RunPython(
            set_default_topic_list,
            reverse_code=migrations.RunPython.noop
        )
    ]
