# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='failed_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일자'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='topics',
            field=models.ManyToManyField(help_text='주제 목록', to='notifications.Topic'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='type',
            field=models.CharField(choices=[('2', 'Email'), ('3', 'Push'), ('1', 'Sms')], help_text='protocol 종류', max_length=1),
        ),
    ]
