# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F, Func, Value


def migrate_notifications(apps, schema_editor):
    Notification = apps.get_model('notifications', 'notification')
    # sms : 1, push: 3, app: 4
    sms = '1'
    app = '4'

    targets = [
        {'from': '매수 신청이 성공적으로 완료되었습니다.', 'to': None, 'protocol': app},
        {'from': '매수가 성공적으로 완료되었습니다.', 'to': '매수가 완료되었습니다.', 'protocol': app},
        {'from': '리밸런싱이 발생하였습니다.', 'to': '리밸런싱이 발생했습니다.', 'protocol': app},
        {'from': '리밸런싱 신청이 성공적으로 완료되었습니다.', 'to': None, 'protocol': app},
        {'from': '리밸런싱이 성공적으로 완료되었습니다.', 'to': '리밸런싱이 완료되었습니다.', 'protocol': app},
        {'from': '매수가 실패하였습니다. 재주문을 실행하세요.', 'to': None, 'protocol': sms},
        {'from': '리밸런싱이 실패하였습니다. 재주문을 실행하세요.', 'to': None, 'protocol': sms},
        {'from': '매수가 완료되었습니다.', 'to': None, 'protocol': app},
        {'from': '리밸런싱이 완료되었습니다.', 'to': None, 'protocol': app},
        {'from': '리밸런싱이 발생하였습니다. 지금 바로 실행하세요.', 'to': '리밸런싱이 발생했습니다.', 'protocol': app}
    ]

    for target in targets:
        from_msg = target.get('from')
        to_msg = target.get('to')
        protocol = target.get('protocol')

        queryset = Notification.objects.filter(message__icontains=from_msg)

        if to_msg:
            queryset.update(
                message=Func(
                    F('message'),
                    Value(from_msg), Value(to_msg),
                    function='replace'
                ),
                protocol=protocol
            )
        else:
            queryset.update(protocol=protocol)


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0004_auto_20180829_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='protocol',
            field=models.CharField(blank=True, choices=[('1', 'SMS'), ('2', 'EMAIL'), ('3', 'PUSH'), ('4', 'APP')],
                                   help_text='전송 방법', max_length=1, null=True),
        ),
        migrations.RunPython(
            migrate_notifications,
            reverse_code=migrations.RunPython.noop
        ),
    ]
