# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_email_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='주제 목록', to='notifications.Topic'),
        ),
    ]
