# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-16 10:52
from __future__ import unicode_literals

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20200221_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='context',
            field=common.models.JSONField(default={}),
        ),
    ]
