# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180830_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '지연중'), (2, '실패'), (3, '대기중'), (4, '진행중'), (5, '완료됨'), (6, '취소됨')], help_text='주문 상태', null=True),
        ),
    ]
