# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_auto_20190425_1615'),
        ('orders', '0007_auto_20181001_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISIN', max_length=12)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '매수'), (2, '환매')], help_text='매수/환매 구분')),
                ('ordered_at', models.DateTimeField(help_text='주문일시', null=True)),
                ('order_price', models.DecimalField(decimal_places=5, help_text='주문금액', max_digits=20)),
                ('paid_at', models.DateTimeField(help_text='결재일시', null=True)),
                ('paid_price', models.DecimalField(decimal_places=5, help_text='결재금액(세금 제외 최종정산 금액)', max_digits=20)),
                ('shares', models.IntegerField(help_text='좌수')),
                ('result', models.PositiveSmallIntegerField(choices=[(1, '성공'), (2, '실패'), (3, '취소됨'), (4, '대기중')], help_text='체결구분')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('account_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='contracts.Contract', to_field='account_alias')),
            ],
            options={
                'db_table': 'orders_order_detail',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='계약사항', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contracts.Contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '지연중'), (2, '실패'), (3, '대기중'), (4, '진행중'), (5, '완료됨'), (6, '취소됨'), (7, '건너뜀')], help_text='주문 상태', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set([('account_alias', 'code', 'type', 'created_at')]),
        ),
    ]
