# Generated by Django 3.0.3 on 2020-12-09 05:09

from django.db import migrations, models

import api.bases.orders.models
import common.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='설정 별칭', max_length=128, unique=True)),
                ('strategies',
                 common.models.JSONField(default=api.bases.orders.models.get_default_strategies, help_text='주문 전략')),
                ('emphasis', models.CharField(
                    choices=[('min_deposit', '예수금 최소화(O(n))'), ('strict_ratio', '비중 최적화(O(n))'),
                             ('optimized_deposit', '예수금 최적화(O(2^n))')], default='optimized_deposit',
                    help_text='주문 수량 결정 로직', max_length=100)),
            ],
        )
    ]
