# Generated by Django 3.0.3 on 2020-12-09 05:16

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial_order_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISIN 코드', max_length=12)),
                ('type',
                 models.CharField(choices=[('1', '매수'), ('2', '매도')], help_text='매매 구분(1: 매수, 2: 매도)', max_length=1)),
                ('ordered_at', models.DateTimeField(help_text='주문 집행 일시')),
                ('order_price', models.IntegerField(help_text='주문금액(원화)')),
                ('order_price_usd', models.FloatField(help_text='주문금액(외화)', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='결제 완료 일시', null=True)),
                ('paid_price', models.IntegerField(blank=True, help_text='결제금액(원화 체결가)', null=True)),
                ('paid_price_usd', models.FloatField(help_text='결제금액(외화 체결가)', null=True)),
                ('shares', models.IntegerField(help_text='좌수')),
                ('result', models.CharField(choices=[('1', '성공'), ('2', '실패'), ('3', '취소'), ('4', '대기')],
                                            help_text='체결 구분(1: 성공, 2: 실패, 3: 취소, 4: 대기)', max_length=1)),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('account_alias', 'ordered_at', 'code', 'type', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(
                    choices=[(1, '지연중'), (2, '실패'), (3, '대기중'), (4, '진행중'), (5, '완료됨'), (6, '취소됨'), (7, '건너뜀')],
                    default=3, help_text='주문상태(1: 지연중, 2: 실패, 3: 대기중, 4: 진행중, 5: 완료됨, 6: 취소됨, 7: 건너뜀)')),
                ('mode', model_utils.fields.StatusField(
                    choices=[('new_order', '신규'), ('sell', '매도'), ('buy', '매수'), ('rebalancing', '리밸런싱')],
                    default='new_order', help_text='주문 종류(new_order: 신규, sell: 매도, buy: 매수, rebalancing: 리밸런싱)',
                    max_length=100, no_check_for_status=True)),
                ('portfolio_id',
                 models.BigIntegerField(blank=True, default=None, help_text='주문 요청 포트폴리오 ID', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='주문 처리 완료 일자', null=True)),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('account_alias', 'created_at')},
            },
        ),
    ]
