# Generated by Django 3.0.3 on 2020-12-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_event_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersetting',
            name='min_base',
            field=models.IntegerField(default=0, help_text='최소 보유 원금'),
        ),
    ]
