# Generated by Django 3.0.3 on 2021-05-28 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_trade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
