# Generated by Django 3.0.3 on 2023-01-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='shares',
            field=models.DecimalField(decimal_places=6, help_text='좌수', max_digits=30),
        ),
    ]
