# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_auto_20180406_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='cert_type',
            field=models.CharField(choices=[('1', 'sms'), ('2', 'accounts'), ('3', 'ars')], max_length=1),
        ),
    ]
