apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
type: Opaque
data:
  # Django
  DJANGO_SECRET_KEY: {{ required "secretKey is a required value." .Values.secrets.secretKey | b64enc | quote }}
  DJANGO_ADMIN_URL: {{ .Values.secrets.adminURL | b64enc | quote }}
  # Database
  DATABASE_DEFAULT_URL: {{ required "databaseDefaultURL is a required value." .Values.secrets.databaseDefaultURL | b64enc | quote }}
  DATABASE_ACCOUNTS_URL: {{ required "databaseAccountsURL is a required value." .Values.secrets.databaseAccountsURL | b64enc | quote }}
  DATABASE_PORTFOLIO_URL: {{ required "databasePortfolioURL is a required value." .Values.secrets.databasePortfolioURL | b64enc | quote }}
  # Cache
  CACHE_DEFAULT_URL: {{ required "cacheDefaultURL is a required value." .Values.secrets.cacheDefaultURL | b64enc | quote }}
  CACHE_PRICE_URL: {{ required "cachePriceURL is a required value." .Values.secrets.cachePriceURL | b64enc | quote }}
  # Celery
  CELERY_BROKER_URL: {{ required "celeryBrokerURL is a required value." .Values.secrets.celeryBrokerURL | b64enc | quote }}
  CELERY_RESULT_BACKEND: {{ required "celeryResultBackend is a required value." .Values.secrets.celeryResultBackend | b64enc | quote }}
  # Celery Flower
{{- if .Values.secrets.celeryFlowerUser }}
  CELERY_FLOWER_USER: {{ .Values.secrets.celeryFlowerUser | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.celeryFlowerPassword }}
  CELERY_FLOWER_PASSWORD: {{ .Values.secrets.celeryFlowerPassword | b64enc | quote }}
{{- end }}
  # Litchi
  LITCHI_BACKEND_API_TOKEN: {{ required "litchiBackendAPIToken is a required value." .Values.secrets.litchiBackendAPIToken | b64enc | quote }}
  # Litchi Account
  LITCHI_ACCOUNT_BACKEND_API_TOKEN: {{ required "litchiAccountBackendAPIToken is a required value." .Values.secrets.litchiAccountBackendAPIToken | b64enc | quote }}