apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWeb.type }}
  ports:
    - port: {{ .Values.serviceWeb.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "django.selectorLabels" . | nindent 4 }}
    role: web
