apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}-flower
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceFlower.type }}
  ports:
    - port: {{ .Values.serviceFlower.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "django.selectorLabels" . | nindent 4 }}
    role: flower
