#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py createsuperuser --noinput
/usr/local/bin/gunicorn oms.wsgi --bind 0.0.0.0:8000 --chdir=/app
