# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20180212_0752'),
        ('contracts', '0002_contract_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='integrate',
            field=models.OneToOneField(blank=True, help_text='금융사 연동코드', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentications.Integrate'),
        ),
    ]
