# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_provisionalcontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionalcontract',
            old_name='account_number',
            new_name='account_alias',
        ),
    ]
