# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 03:40
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_auto_20180411_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcontract',
            name='step',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='진행상태 구분', null=True),
        ),
    ]
