# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 04:26
from __future__ import unicode_literals

import api.bases.contracts.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contract_firm_agreement_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='조건 이름', max_length=128, unique=True)),
                ('field_1', models.CharField(blank=True, max_length=128, null=True)),
                ('field_2', models.CharField(blank=True, max_length=128, null=True)),
                ('field_3', models.CharField(blank=True, max_length=128, null=True)),
                ('field_4', models.CharField(blank=True, max_length=128, null=True)),
                ('field_5', models.CharField(blank=True, max_length=128, null=True)),
                ('field_6', models.CharField(blank=True, max_length=128, null=True)),
                ('field_7', models.CharField(blank=True, max_length=128, null=True)),
                ('field_8', models.CharField(blank=True, max_length=128, null=True)),
                ('field_9', models.CharField(blank=True, max_length=128, null=True)),
                ('field_10', models.CharField(blank=True, max_length=128, null=True)),
                ('contract_file', models.FileField(blank=True, help_text='계약서 파일', null=True, upload_to='contracts/%Y%m%d', validators=[api.bases.contracts.models.validate_file_extension])),
                ('appendix_file_1', models.FileField(blank=True, help_text='별첨 파일 1', null=True, upload_to='contracts/%Y%m%d/appendix', validators=[api.bases.contracts.models.validate_file_extension])),
                ('appendix_file_2', models.FileField(blank=True, help_text='별첨 파일 2', null=True, upload_to='contracts/%Y%m%d/appendix', validators=[api.bases.contracts.models.validate_file_extension])),
                ('appendix_file_3', models.FileField(blank=True, help_text='별첨 파일 3', null=True, upload_to='contracts/%Y%m%d/appendix', validators=[api.bases.contracts.models.validate_file_extension])),
                ('is_default', models.BooleanField(default=False, help_text='기본 계약 조건 여부')),
                ('is_publish', models.BooleanField(default=False, help_text='발행 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='firm_agreement_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='출금이체 동의 날짜', null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcontract',
            name='is_contract',
            field=models.BooleanField(default=False, help_text='계약 해지 여부'),
        ),
        migrations.AddField(
            model_name='contract',
            name='condition',
            field=models.ForeignKey(blank=True, help_text='세부 계약조건', null=True, on_delete=django.db.models.deletion.PROTECT, to='contracts.Condition'),
        ),
    ]
