# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0014_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('start_at', models.DateTimeField(help_text='예약실행 시작일')),
                ('status', model_utils.fields.StatusField(choices=[('reserved', '예약'), ('reserve_failed', '예약 실패'), ('processing', '진행중'), ('success', '성공'), ('canceled', '취소'), ('condition_failed', '사전 조건 실패'), ('failed', '실패')], default='reserved', help_text='실행 상태', max_length=100, no_check_for_status=True)),
                ('action', model_utils.fields.StatusField(choices=[('rebalancing', '리밸런싱 발생')], default='rebalancing', help_text='실행 종류', max_length=100, no_check_for_status=True)),
                ('task_id', models.UUIDField(blank=True, editable=False, help_text='실행된 task', null=True)),
                ('contract', models.ForeignKey(help_text='계약', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_actions', to='contracts.Contract')),
                ('register', models.ForeignKey(editable=False, help_text='등록자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_reserved_action',
            },
        ),
    ]
