# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 10:14
from __future__ import unicode_literals

from django.db import migrations, models


def set_canceled_at(apps, schema_editor):
    Contract = apps.get_model('contracts', 'contract')
    for contract in Contract.objects.filter(is_canceled=True):
        contract.canceled_at = contract.updated_at
        contract.save(update_fields=['canceled_at'])


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0015_reservedaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='canceled_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='해지일', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.IntegerField(choices=[(0, '해지됨'), (1, '정상 유지'),
                                               ('Firmbanking', [(2, '펌뱅킹 등록 중'), (20, '펌뱅킹 등록 실패'), (21, '펌뱅킹 등록 완료')]),
                                               ('Withdraw', [(3, '출금이체 진행 중'), (30, '출금이체 실패'), (31, '출금이체 완료')])],
                                      default=1, help_text='계약 상태'),
        ),
        migrations.RunPython(
            set_canceled_at,
            reverse_code=migrations.RunPython.noop
        ),
    ]
