# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_auto_20180830_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='force_rebalancing',
            field=models.BooleanField(default=False, help_text='강제 리밸런싱 발생 여부'),
        ),
    ]
