# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-07 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_contract_to_provisional(apps, schema_editor):
    Contract = apps.get_model('contracts', 'contract')
    Provisional = apps.get_model('contracts', 'provisionalcontract')

    for contract in Contract.objects.all():
        try:
            prov = Provisional.objects.get(user=contract.user, account_alias=contract.account_alias)
            prov.contract = contract
            prov.save(update_fields=['contract'])
        except:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0020_auto_20181203_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcontract',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='provisional', to='contracts.Contract'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='tr_reg_date',
            field=models.PositiveIntegerField(blank=True,
                                              choices=[(1, '매월 1일'), (5, '매월 5일'), (10, '매월 10일'), (15, '매월 15일'),
                                                       (20, '매월 20일'), (25, '매월 25일')], help_text='자동이체 처리일',
                                              null=True),
        ),
        migrations.RunPython(
            set_contract_to_provisional,
            reverse_code=migrations.RunPython.noop
        ),
    ]
