# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_rebalancing_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('prev_deposit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'db_table': 'contracts_assets',
            },
        ),
        migrations.CreateModel(
            name='AssetsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('buy_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('shares', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=5, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'db_table': 'contracts_assets_detail',
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='account_alias',
            field=models.CharField(help_text='계좌대체번호', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.IntegerField(choices=[(0, '해지됨'), (1, '정상 유지'), ('Firmbanking', [(2, '펌뱅킹 등록 중'), (20, '펌뱅킹 등록 실패'), (21, '펌뱅킹 등록 완료')]), ('Withdraw', [(3, '출금이체 진행 중'), (30, '출금이체 실패'), (31, '출금이체 완료')]), ('Vendor', [(4, '협력사 해지 대기')])], default=1, help_text='계약 상태'),
        ),
        migrations.AddField(
            model_name='assetsdetail',
            name='account_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_detail', to='contracts.Contract', to_field='account_alias'),
        ),
        migrations.AddField(
            model_name='assets',
            name='account_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='contracts.Contract', to_field='account_alias'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsdetail',
            unique_together=set([('account_alias', 'code', 'created_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='assets',
            unique_together=set([('account_alias', 'created_at')]),
        ),
    ]
