# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 08:14
from __future__ import unicode_literals

import api.bases.contracts.models
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_auto_20190319_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='account_alias',
            field=models.CharField(default=api.bases.contracts.models.create_contract_number, help_text='계좌대체번호', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='account_number',
            field=fernet_fields.fields.EncryptedCharField(default=api.bases.contracts.models.create_contract_number, help_text='계좌번호', max_length=128),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.IntegerField(choices=[(0, '해지됨'), (1, '정상 유지'), ('Firmbanking', [(2, '펌뱅킹 등록 중'), (20, '펌뱅킹 등록 실패'), (21, '펌뱅킹 등록 완료')]), ('Withdraw', [(3, '출금이체 진행 중'), (30, '출금이체 실패'), (31, '출금이체 완료')]), ('Vendor', [(4, '협력사 해지 대기'), (41, '협력사 계좌개설 대기')])], default=41, help_text='계약 상태'),
        ),
        migrations.AlterField(
            model_name='provisionalcontract',
            name='account_alias',
            field=models.CharField(blank=True, help_text='임시계좌번호', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcontract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('EA', 'ETF'), ('FA', '펀드'), ('PA', '연금')], help_text='임시 계약 종류', max_length=2, null=True),
        ),
    ]
