# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-10 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_auto_20190709_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='ci',
        ),
    ]
