# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_remove_contract_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='doc_path',
            field=models.CharField(blank=True, help_text='계약 문서 경로', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='sign',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='서명 정보 Base64', null=True),
        ),
    ]
