# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_auto_20200803_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='operation_type',
            field=models.CharField(choices=[('A', '자문'), ('P', '일임')], default='A', help_text='자문/일임 구분', max_length=1),
        ),
    ]
