# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-05-04 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0036_rebalancingqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='catalog_id',
            field=models.IntegerField(blank=True, help_text='가입 상품 ID', null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='strategy_code',
            field=models.IntegerField(blank=True, help_text='운영 전략 코드', null=True),
        ),
    ]
