# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_auto_20210504_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='acct_completed_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='계좌생성 완료 날짜', null=True),
        ),
    ]
