# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-07-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0039_term_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('status', models.IntegerField(
                    choices=[('Pension', [(10, '이체신청'), (11, '가입확인'), (12, '이체예정'), (13, '이체접수'),
                                          (14, '이체납입명세'), (15, '이체실패'), (16, '자동취소')])], default=10,
                    help_text='이전 상태')),
                ('account_number', fernet_fields.fields.EncryptedCharField(help_text='상대 계좌번호', max_length=128)),
                ('product_type', models.CharField(choices=[('Pension', [('1', 'IRP'), ('2', '연금저축')])], default=None,
                                                  help_text='상대 계좌 타입', max_length=10, null=True)),
                ('vendor', models.CharField(blank=True, help_text='상대 기관명', max_length=100, null=True)),
                ('completed_at', models.DateField(default=None, help_text='이전 완료일', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(help_text='계약명', max_length=40),
        ),
        migrations.AlterField(
            model_name='term',
            name='contract_type',
            field=models.ForeignKey(blank=True, db_column='contract_type', help_text='계약종류', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='contract_type',
                                    to='contracts.ContractType'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='contract',
            field=models.ForeignKey(help_text='계약', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transfer', to='contracts.Contract'),
        ),
    ]
