# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_contracttype_is_orderable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='수수료 적용 조건명', max_length=32)),
                ('amount', models.IntegerField(blank=True, default=0, help_text='수수료액', null=True)),
                ('rate', models.FloatField(blank=True, default=0, help_text='수수료율', null=True)),
                ('min_max', models.IntegerField(choices=[(1, 'Min'), (2, 'Max'), (3, None)], default=1, help_text='최소, 최대 구분')),
                ('effective_date', models.DateField(blank=True, help_text='약관 적용 일자', null=True)),
                ('is_free', models.BooleanField(default=False, help_text='무료 적용 여부')),
                ('period_int', models.IntegerField(blank=True, default=0, help_text='무료 적용 기간(정수)', null=True)),
                ('period_type', models.IntegerField(choices=[(1, 'days'), (2, 'weeks'), (3, 'months'), (4, 'years')], default=3, help_text='무료 적용 기간(단위)')),
                ('is_static', models.BooleanField(default=True, help_text='기준일 고정 여부')),
                ('is_default', models.BooleanField(default=False, help_text='기본 수수료 조건 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('term', models.ForeignKey(help_text='계약 약관', on_delete=django.db.models.deletion.CASCADE, to='contracts.Term')),
            ],
            options={
                'db_table': 'term_detail',
            },
        ),
        migrations.AddField(
            model_name='contracttype',
            name='fee_period',
            field=models.IntegerField(choices=[(1, 'yearly'), (2, 'monthly'), (3, 'quarterly')], default=1, help_text='수수료 수취 기간 단위'),
        ),
        migrations.AddField(
            model_name='contract',
            name='term_detail',
            field=models.ForeignKey(blank=True, help_text='수수료 적용 조건', null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.TermDetail'),
        ),
    ]
