# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-11-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(db_column='status', help_text='계약 상태',
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='contracts',
                                    to='contracts.ContractStatus'),
        ),
    ]
