# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-01-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0053_add_transfer_canceled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='is_bankingplus',
            field=models.BooleanField(default=False, help_text='뱅킹플러스 사용 유무'),
        ),
    ]
