# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-08-12 00:59
from __future__ import unicode_literals

import api.bases.agreements.models
import api.bases.contracts.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


def set_default_agreementGroup(apps, schema_editor):
    AgreementGroup = apps.get_model('agreements', 'AgreementGroup')

    AgreementGroup.objects.create(title='-', is_default=True, is_publish=True)


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20201123_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='동의 조건 이름', max_length=128)),
                ('is_default', models.BooleanField(default=False, help_text='기본 동의 조건 여부')),
                ('is_publish', models.BooleanField(default=False, help_text='발행 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='동의 타입 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='동의 타입 수정일')),
            ],
        ),
        migrations.RunPython(
            set_default_agreementGroup,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='type',
            name='agreement_file',
            field=models.FileField(blank=True, help_text='동의서 파일', null=True, upload_to='agreements/%Y%m%d', validators=[api.bases.contracts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(help_text='동의 타입 코드', max_length=60),
        ),
        migrations.AddField(
            model_name='agreement',
            name='agreement_group',
            field=models.ForeignKey(default=api.bases.agreements.models.get_agreement_group_default_title, help_text='동의 타입 그룹', on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='agreements.AgreementGroup'),
        ),
        migrations.AddField(
            model_name='type',
            name='agreement_group',
            field=models.ForeignKey(default=api.bases.agreements.models.get_agreement_group_default_title, help_text='각 동의서 리스트', on_delete=django.db.models.deletion.PROTECT, related_name='types', to='agreements.AgreementGroup'),
        ),
    ]
