#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

celery flower \
    --app=oms.celery \
    --url_prefix=flower \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
