# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def set_default_order_status_list(apps, schema_editor):
    OrderStatus = apps.get_model('orders', 'orderstatus')

    order_status = ['pending', 'failed', 'on-hold', 'processing', 'completed', 'cancelled']

    for status in order_status:
        row = OrderStatus(name=status)
        row.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mode', models.CharField(help_text='주문 구분', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='주문 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='업데이트 일자')),
                ('order_item', models.BigIntegerField(help_text='주문 항목(port_seq)')),
                ('order_rep_id', models.ForeignKey(blank=True, help_text='주문 처리 계정 id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_reps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='고객', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            set_default_order_status_list,
            reverse_code=migrations.RunPython.noop
        )
    ]
