# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='계약사항', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='contracts.Contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, help_text='주문 상태', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.OrderStatus'),
        ),
    ]
