# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 07:01
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


def set_modes(apps, schema_editor):
    Order = apps.get_model('orders', 'order')
    Order.objects.filter(mode='new order').update(mode='new_order')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180327_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', '-completed_at')},
        ),
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='new_order', help_text='주문 구분', max_length=100, no_check_for_status=True),
        ),
        migrations.RunPython(
            set_modes,
            reverse_code=migrations.RunPython.noop
        ),
    ]
