# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180830_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
