# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-20 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_remove_contract_ci'),
        ('orders', '0008_auto_20190426_1321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set([('account_alias', 'ordered_at', 'code', 'type', 'created_at')]),
        ),
    ]
