# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-05-25 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0037_auto_20210504_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUniverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('strategy_code', models.CharField(help_text='전략구분', max_length=2)),
                ('code', models.CharField(help_text='중목코드', max_length=12)),
                ('asset_name', models.CharField(help_text='종목명', max_length=128)),
                ('description', models.TextField(help_text='종목설명')),
            ],
        ),
        migrations.CreateModel(
            name='HoldingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('code', models.CharField(help_text='중목코드', max_length=12)),
                ('asset_name', models.CharField(help_text='종목명', max_length=128)),
                ('shares', models.FloatField(help_text='종목수량', null=True)),
                ('acquisition_price', models.DecimalField(decimal_places=5, help_text='취득단가', max_digits=20, null=True)),
                ('market_price', models.DecimalField(decimal_places=5, help_text='시장가격', max_digits=20, null=True)),
                ('balance', models.DecimalField(decimal_places=5, help_text='보유잔액', max_digits=20)),
                ('weight', models.DecimalField(decimal_places=4, help_text='보유비중', max_digits=5, null=True)),
                ('asset_class_name', models.CharField(help_text='자산군명칭', max_length=128)),
                ('account_alias', models.ForeignKey(help_text='계약', on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', to_field='account_alias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('strategy_code', models.IntegerField(help_text='전략구분')),
                ('port_risk_type', models.IntegerField(help_text='포트폴리오 위험 유형')),
                ('qtr_buy_amount', models.DecimalField(decimal_places=5, help_text='해당 분기 매수금액 합계(원화기준)', max_digits=20)),
                ('qtr_sell_amount', models.DecimalField(decimal_places=5, help_text='해당 분기 매도금액 합계(원화기준)', max_digits=20)),
                ('qtr_turnover', models.DecimalField(decimal_places=5, help_text='해당 분기 매매회전율(원화기준)', max_digits=20)),
                ('cum_buy_amount', models.DecimalField(decimal_places=5, help_text='누적기간 매수금액 합계(원화기준)', max_digits=20)),
                ('cum_sell_amount', models.DecimalField(decimal_places=5, help_text='누적기간 매도금액 합계(원화기준)', max_digits=20)),
                ('cum_turnover', models.DecimalField(decimal_places=5, help_text='누적기간 매매회원율(원화기준)', max_digits=20)),
                ('top_holdings_code_1', models.CharField(help_text='투자일임재산 평가액 기준 1위 종목코드', max_length=12, null=True)),
                ('top_holdings_code_2', models.CharField(help_text='투자일임재산 평가액 기준 2위 종목코드', max_length=12, null=True)),
                ('top_holdings_code_3', models.CharField(help_text='투자일임재산 평가액 기준 3위 종목코드', max_length=12, null=True)),
                ('return_3m', models.DecimalField(decimal_places=12, help_text='3개월 수익률', max_digits=22)),
                ('return_6m', models.DecimalField(decimal_places=12, help_text='6개월 수익률', max_digits=22)),
                ('return_9m', models.DecimalField(decimal_places=12, help_text='9개월 수익률', max_digits=22)),
                ('return_12m', models.DecimalField(decimal_places=12, help_text='12개월 수익률', max_digits=22)),
                ('return_cum', models.DecimalField(decimal_places=12, help_text='누적 수익률', max_digits=22)),
                ('qtr_commission', models.DecimalField(decimal_places=5, help_text='해당 분기 매매 수수료', max_digits=20)),
                ('qtr_tax', models.DecimalField(decimal_places=5, help_text='해당분기 각종세금(제세금, 배당에 대한 해외 원천세 포함)', max_digits=20)),
                ('qtr_other_cost', models.DecimalField(decimal_places=5, help_text='해당 분기 각종비용(제비용)', max_digits=20)),
                ('qtr_total_cost', models.DecimalField(decimal_places=5, help_text='해당 분기 총비용', max_digits=20)),
                ('cum_commission', models.DecimalField(decimal_places=5, help_text='누적기간 매매수수료', max_digits=20)),
                ('cum_tax', models.DecimalField(decimal_places=5, help_text='누적기간 매매수수료(제세금, 배당에 대한 해외 원천세 포함)', max_digits=20)),
                ('cum_other_cost', models.DecimalField(decimal_places=5, help_text='누적기간 각종비용(제비용)', max_digits=20)),
                ('cum_total_cost', models.DecimalField(decimal_places=5, help_text='누적기간 총비용', max_digits=20)),
                ('baseline_date', models.DateField(help_text='정보제공기준일 (default: 분기말, 운용중지: 운용중지 전일)')),
                ('account_alias', models.ForeignKey(help_text='계약', on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', to_field='account_alias')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementReportHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('strategy_code', models.IntegerField(help_text='전략구분')),
                ('strategy', models.CharField(help_text='시장상황 및 투자전략[FTMR02]', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('strategy_code', models.CharField(help_text='전략구분', max_length=2)),
                ('name', models.CharField(help_text='이름(한글)', max_length=30)),
                ('career', models.CharField(help_text='주요경력 및 자격(한글)', max_length=400)),
                ('is_certified', models.CharField(help_text='유지보수 전문인력요건 충족여부(한글)', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoboAdvisorDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(help_text='알고리즘명(한글 포함)', max_length=32)),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('strategy_code', models.CharField(help_text='전략구분', max_length=2)),
                ('inception_date', models.CharField(help_text='운용개시일', max_length=8)),
                ('contract_quantity', models.IntegerField(help_text='분기말 기준 일임계약수')),
                ('aum', models.BigIntegerField(help_text='분기말 기준 일임계약수')),
                ('certified_record', models.CharField(help_text='주요경력 및 자격', max_length=32)),
                ('phone', models.CharField(help_text='회사 전화번호', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('trade_type', models.CharField(help_text='매매구분', max_length=4)),
                ('asset_name', models.CharField(help_text='종목명', max_length=128)),
                ('trade_date', models.DateField(help_text='매매일자(YYYMMDD)')),
                ('shares', models.FloatField(help_text='종목수량')),
                ('trade_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('trade_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('trade_commission', models.DecimalField(decimal_places=5, max_digits=20)),
                ('trade_tax', models.DecimalField(decimal_places=5, max_digits=20)),
                ('account_alias', models.ForeignKey(help_text='계약', on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', to_field='account_alias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='managementreportheader',
            unique_together=set([('year', 'quarter', 'strategy_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='assetuniverse',
            unique_together=set([('year', 'quarter', 'strategy_code', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='managementreport',
            unique_together=set([('year', 'quarter', 'account_alias')]),
        ),
    ]
