# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-05-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementreport',
            name='return_12m',
            field=models.DecimalField(decimal_places=12, help_text='12개월 수익률', max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='managementreport',
            name='return_3m',
            field=models.DecimalField(decimal_places=12, help_text='3개월 수익률', max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='managementreport',
            name='return_6m',
            field=models.DecimalField(decimal_places=12, help_text='6개월 수익률', max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='managementreport',
            name='return_9m',
            field=models.DecimalField(decimal_places=12, help_text='9개월 수익률', max_digits=22, null=True),
        ),
    ]
