# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-08-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementreportheader',
            name='strategy',
            field=models.TextField(help_text='시장상황 및 투자전략[FTMR02]'),
        ),
        migrations.AlterField(
            model_name='managerdetail',
            name='career',
            field=models.TextField(help_text='주요경력 및 자격(한글)'),
        ),
        migrations.AlterUniqueTogether(
            name='assetuniverse',
            unique_together=set([('year', 'quarter', 'code')]),
        ),
    ]
