# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-08-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_update_report_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementreport',
            name='baseline_date',
            field=models.DateTimeField(help_text='정보제공기준일 (default: 분기말, 운용중지: 운용중지 전일)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='effective_date',
            field=models.DateTimeField(help_text='첫주문 시작일(계약 발효일)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='from_date',
            field=models.DateTimeField(help_text='조회 시작일'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='to_date',
            field=models.DateTimeField(help_text='조회 종료일'),
        ),
        migrations.AlterField(
            model_name='roboadvisordesc',
            name='inception_date',
            field=models.DateTimeField(help_text='운용개시일'),
        ),
        migrations.AlterField(
            model_name='tradingdetail',
            name='trade_date',
            field=models.DateTimeField(help_text='매매일자'),
        ),
    ]
