# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-08-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_auto_20210504_1753'),
        ('reports', '0003_add_report_flag_and_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('year', models.CharField(help_text='기준년도', max_length=4)),
                ('quarter', models.CharField(help_text='기준분기', max_length=1)),
                ('base_amount', models.IntegerField(help_text='투자원금')),
                ('evaluation_amount', models.IntegerField(help_text='평가금액')),
                ('acc_input_amount', models.IntegerField(help_text='누적입금액')),
                ('acc_output_amount', models.IntegerField(help_text='누적출금액')),
                ('acc_gross_loss', models.IntegerField(help_text='누적수익금')),
                ('acc_return', models.DecimalField(decimal_places=4, help_text='누적수익률', max_digits=8)),
                ('period_input_amount', models.IntegerField(help_text='기간출금액')),
                ('period_output_amount', models.IntegerField(help_text='기간출금액')),
                ('period_gross_loss', models.IntegerField(help_text='기간수익')),
                ('period_return', models.DecimalField(decimal_places=4, help_text='기간수익률', max_digits=8)),
                ('annualized_return', models.DecimalField(decimal_places=4, help_text='연환산수익률', max_digits=8, null=True)),
                ('investment_days', models.IntegerField(help_text='투자기간')),
                ('from_date', models.DateField(help_text='조회 시작일')),
                ('to_date', models.DateField(help_text='조회 종료일')),
                ('effective_date', models.DateField(help_text='첫주문 시작일(계약 발효일)')),
                ('account_alias', models.ForeignKey(help_text='계약', on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', to_field='account_alias')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('year', 'quarter', 'account_alias')]),
        ),
    ]
