# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 07:04
from __future__ import unicode_literals

import api.bases.contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contract_number', models.CharField(default=api.bases.contracts.models.create_contract_number, editable=False, help_text='계약 번호', max_length=20)),
                ('contract_type', models.CharField(choices=[('EA', 'ETF Advisor'), ('FA', 'FUND Advisor')], help_text='계약 종류', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='계약 체결일')),
                ('last_payment_at', models.DateTimeField(blank=True, help_text='마지막 결제 확인일', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='계약 유지 상태')),
                ('user', models.ForeignKey(help_text='계약자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
