# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_canceled',
            field=models.BooleanField(default=False, help_text='계약 취소 여부'),
        ),
    ]
