# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_default_risk_type(apps, schema_editor):
    Contract = apps.get_model('contracts', 'contract')

    for row in Contract.objects.all():
        if row.user.profile.risk_type is not None:
            row.risk_type = row.user.profile.risk_type
            row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0003_contract_integrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='risk_type',
            field=models.IntegerField(help_text='위험 성향', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='integrate',
            field=models.OneToOneField(blank=True, help_text='금융사 연계정보', null=True,
                                       on_delete=django.db.models.deletion.SET_NULL, to='authentications.Integrate'),
        ),
        migrations.RunPython(
            set_default_risk_type,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='contract',
            name='last_payment_at',
        ),
    ]
