# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0005_remove_contract_integrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_active',
        ),
        migrations.AddField(
            model_name='contract',
            name='account_ci',
            field=fernet_fields.fields.EncryptedCharField(default=None, help_text='계좌번호 CI', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='account_number',
            field=fernet_fields.fields.EncryptedCharField(default=None, help_text='계좌번호', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(help_text='증권사', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='계약 UUID', primary_key=True, serialize=False, unique=True),
        ),
    ]
