# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20180406_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='account_ci',
        ),
        migrations.AddField(
            model_name='contract',
            name='account_alias',
            field=models.CharField(default=None, help_text='계좌대체번호', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='ci',
            field=models.CharField(default=None, help_text='계좌 유저의 증권사 CI', max_length=128),
            preserve_default=False,
        ),
    ]
