# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_default_condition(apps, schema_editor):
    Contract = apps.get_model('contracts', 'contract')
    Condition = apps.get_model('contracts', 'condition')

    condition = Condition.objects.create(title='default', is_default=True, is_publish=True)
    Contract.objects.all().update(condition=condition)


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0012_auto_20180730_0426'),
    ]

    operations = [
        migrations.RunPython(
            set_default_condition,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='contract',
            name='condition',
            field=models.ForeignKey(help_text='세부 계약조건', on_delete=django.db.models.deletion.PROTECT,
                                    to='contracts.Condition'),
        ),
    ]
