# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 12:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_auto_20181203_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contracts.Contract')),
                ('period_year', models.PositiveSmallIntegerField(help_text='가입 기간', validators=[django.core.validators.MinValueValidator(5)])),
                ('expired_at', models.DateTimeField(help_text='가입 만기일')),
                ('received_at', models.DateTimeField(blank=True, help_text='수령개시 희망일(연금)', null=True)),
                ('tr_amount', models.PositiveIntegerField(blank=True, help_text='자동이체 월 납부금', null=True)),
                ('tr_reg_date', models.PositiveIntegerField(blank=True, choices=[(1, '매월 1일'), (5, '매월 5일'), (15, '매월 15일'), (20, '매월 20일'), (25, '매월 25일')], help_text='자동이체 처리일', null=True)),
                ('tr_expired_at', models.DateTimeField(blank=True, help_text='월 납부 이체 기간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.ForeignKey(help_text='계약 약관 조건', on_delete=django.db.models.deletion.PROTECT, related_name='term', to='contracts.Term'),
        ),
    ]
