# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-24 05:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_auto_20181207_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='payment_limit',
            field=models.IntegerField(blank=True, help_text='납입 한도', null=True, validators=[django.core.validators.MaxValueValidator(18000000)]),
        ),
        migrations.AddField(
            model_name='condition',
            name='set_limit',
            field=models.IntegerField(blank=True, help_text='설정 한도', null=True, validators=[django.core.validators.MaxValueValidator(18000000)]),
        ),
    ]
