# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_auto_20190422_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedaction',
            name='register',
            field=models.ForeignKey(editable=False, help_text='등록자', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
