# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-04 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_auto_20200805_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.IntegerField(choices=[(0, '해지됨'), (1, '정상 유지'), ('Firmbanking', [(2, '펌뱅킹 등록 중'), (20, '펌뱅킹 등록 실패'), (21, '펌뱅킹 등록 완료')]), ('Account', [(22, '해지 매도 진행 중'), (23, '해지 매도 실패'), (24, '해지 매도 완료'), (25, '환전 진행 중'), (26, '환전 실패'), (27, '환전 완료')]), ('Withdraw', [(3, '출금이체 진행 중'), (30, '출금이체 실패'), (31, '출금이체 완료')]), ('Vendor', [(4, '협력사 해지 대기'), (41, '협력사 계좌개설 대기'), (42, '주문대리인 등록 대기'), (43, '인증토큰 발급 실패'), (44, '증권사 식별정보 조회 실패'), (45, '전자문서 전달 실패'), (46, '주문대리인 등록 실패'), (47, '주문대리인 해지중 토큰발급 실패'), (48, '주문대리인 해지 대기'), (49, '주문대리인 해지 실패')])], default=41, help_text='계약 상태'),
        ),
    ]
