# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-03-25 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_auto_20210205_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebalancingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '지연중'), (2, '실패'), (3, '대기중'), (4, '진행중'), (5, '완료됨'), (6, '취소됨'), (7, '건너뜀')], help_text='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('completed_at', models.DateTimeField(blank=True, help_text='완료일', null=True)),
                ('contract', models.ForeignKey(help_text='계약', on_delete=django.db.models.deletion.CASCADE, related_name='reb_requests', to='contracts.Contract')),
            ],
        ),
    ]
