# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0041_transfer_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='is_orderable',
            field=models.BooleanField(default=False, help_text='주문 가능 유무'),
        ),
    ]
