# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-20 06:08
from __future__ import unicode_literals

from django.db import migrations
import datetime


def add_contents(apps, schema_editor):
    TermDetail = apps.get_model('contracts', 'termdetail')
    Term = apps.get_model('contracts', 'term')
    ContractType = apps.get_model('contracts', 'contracttype')

    default_yearly_term, created = Term.objects.get_or_create(title='default',
                                                              defaults={
                                                                  'field_1': 'v1',
                                                                  'is_default': True,
                                                                  'is_publish': True,
                                                                  'contract_type': None
                                                              })
    default_monthly_term, created = Term.objects.get_or_create(title='2022',
                                                               defaults={
                                                                   'field_1': 'v2',
                                                                   'is_default': True,
                                                                   'is_publish': True,
                                                                   'contract_type': None
                                                               })
    pension_contract_type = ContractType.objects.filter(code='KBPA').first()
    if pension_contract_type is None:
        pension_contract_type = ContractType.objects.create(code='KBPA', name='연금', universe=2083, asset_type='kr_etf',
                                                            fee_type=2, reb_interval=90, resend_interval=5,
                                                            delay_interval=0, date_method=1, operation_type='A',
                                                            is_orderable=1, fee_period=1)

    pension_term = Term.objects.create(title='KBPA_v1', field_1='v1', field_2='yearly', field_3='performance',
                                       is_default=True, is_publish=True, contract_type=pension_contract_type)

    TermDetail.objects.create(title='default_yearly', term=default_yearly_term, amount=0, rate=0.15, min_max=3,
                              effective_date=datetime.date(2018, 8, 17), is_default=True)
    TermDetail.objects.create(title='default_monthly', term=default_monthly_term, amount=4900, rate=0.001, min_max=1,
                              effective_date=datetime.date(2022, 7, 29), period_int=3, period_type=3, is_default=True)
    TermDetail.objects.create(title='default_pension', term=pension_term, amount=0, rate=0.09, min_max=3,
                              is_static=False,
                              effective_date=datetime.date(2022, 10, 17), period_int=1, period_type=4, is_default=True)


def set_content(apps, schema_editor):
    Contract = apps.get_model('contracts', 'contract')
    TermDetail = apps.get_model('contracts', 'termdetail')

    default_yearly_term_detail = TermDetail.objects.get(title='default_yearly')
    default_monthly_term_detail = TermDetail.objects.get(title='default_monthly')
    for contract in Contract.objects.all():
        if contract.term.title == '2022':
            contract.term_detail = default_monthly_term_detail
        else:
            contract.term_detail = default_yearly_term_detail
        contract.save(update_fields=['term_detail'])


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0043_add_term_detail'),
    ]
    operations = [
        migrations.RunPython(
            add_contents,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            set_content,
            reverse_code=migrations.RunPython.noop
        ),
    ]
