# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-10-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_alter_termdetail_field_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='company',
            field=models.CharField(blank=True, help_text='기관명', max_length=20, null=True),
        )
    ]
