# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-10-04 04:52
from __future__ import unicode_literals

from django.db import migrations
import datetime

from django.utils import timezone


def add_terms(apps, schema_editor):
    Term = apps.get_model('contracts', 'term')
    ContractType = apps.get_model('contracts', 'contracttype')
    TermDetail = apps.get_model('contracts', 'termdetail')

    contract_type_FA = ContractType.objects.get(code='FA')
    contract_type_PA = ContractType.objects.get(code='PA')
    contract_type_EA = ContractType.objects.get(code='EA')

    contract_type_OEA, created = ContractType.objects.get_or_create(code='OEA',
                                                                    defaults={
                                                                        'name': '글로벌ETF',
                                                                        'fee_type': 2,
                                                                        'universe': 1080,
                                                                        'asset_type': 'etf'
                                                                    })
    contract_type_CMA, created = ContractType.objects.get_or_create(code='CMA',
                                                                    defaults={
                                                                        'name': 'CMA',
                                                                        'fee_type': 4,
                                                                        'universe': -1,
                                                                        'asset_type': 'kr_fund'
                                                                    })

    FA_v1 = Term.objects.create(title='FA_v1', field_1='v1', field_2='yearly', field_3='performance', is_default=True,
                                is_publish=True, contract_type=contract_type_FA)
    PA_v1 = Term.objects.create(title='PA_v1', field_1='v1', field_2='yearly', field_3='performance', is_default=True,
                                is_publish=True, contract_type=contract_type_PA)
    EA_v1 = Term.objects.create(title='EA_v1', field_1='v1', field_2='yearly', field_3='performance', is_default=True,
                                is_publish=True, contract_type=contract_type_EA)
    OEA_v1 = Term.objects.create(title='OEA_v1', field_1='v1', field_2='yearly', field_3='performance', is_publish=True,
                                 contract_type=contract_type_OEA)
    CMA_v1 = Term.objects.create(title='CMA_v1', field_1='v1', field_2='yearly', field_3='performance', is_default=True,
                                 is_publish=True, contract_type=contract_type_CMA)
    OEA_v2 = Term.objects.get(title='default')
    OEA_v2.title = 'OEA_v2'
    OEA_v2.field_1 = 'v2'
    OEA_v2.field_2 = 'monthly'
    OEA_v2.field_3 = 'periodic'
    OEA_v2.save(update_fields=['title', 'field_1', 'field_2', 'field_3'])

    TermDetail.objects.create(title='1', term=FA_v1, amount=0, rate=0.15, min_max=3,
                              effective_date=datetime.date(2018, 8, 17), is_default=True)
    TermDetail.objects.create(title='1', term=PA_v1, amount=0, rate=0.15, min_max=3,
                              effective_date=datetime.date(2018, 8, 17), is_default=True)
    TermDetail.objects.create(title='1', term=EA_v1, amount=0, rate=0.15, min_max=3,
                              effective_date=datetime.date(2018, 8, 17), is_default=True)
    TermDetail.objects.create(title='1', term=OEA_v1, amount=0, rate=0.15, min_max=3,
                              effective_date=datetime.date(2018, 8, 17), is_default=True)
    TermDetail.objects.create(title='1', term=CMA_v1, amount=0, rate=0.15, min_max=3,
                              effective_date=datetime.date(2018, 8, 17), is_default=True)

    monthly_term_detail = TermDetail.objects.get(title='default_monthly')
    monthly_term_detail.title = '1'
    monthly_term_detail.period_int = 155
    monthly_term_detail.period_type = 1
    monthly_term_detail.save(update_fields=['title', 'period_int', 'period_type'])

    kbpa_term_detail = TermDetail.objects.get(title='default_pension')
    kbpa_term_detail.title = '1'
    kbpa_term_detail.save(update_fields=['title'])


def set_term(apps, schema_editor):
    Contract = apps.get_model('contracts', 'contract')
    Term = apps.get_model('contracts', 'term')
    TermDetail = apps.get_model('contracts', 'termdetail')

    term_FA = Term.objects.get(title='FA_v1')
    term_PA = Term.objects.get(title='PA_v1')
    term_EA = Term.objects.get(title='EA_v1')
    term_OEA = Term.objects.get(title='OEA_v1')
    term_OEA_v2 = Term.objects.get(title='OEA_v2')
    term_KBPA = Term.objects.get(title='KBPA_v1')
    term_CMA = Term.objects.get(title='CMA_v1')

    term_dict = {
        'FA': term_FA,
        'PA': term_PA,
        'EA': term_EA,
        'OEA': term_OEA,
        'KBPA': term_KBPA,
        'CMA': term_CMA
    }

    for contract in Contract.objects.all():
        if contract.contract_type.code == 'OEA':
            if contract.created_at < datetime.datetime(2022, 7, 28, 15, tzinfo=timezone.utc):
                contract.term = term_OEA
                contract.term_detail = TermDetail.objects.get(title='1', term=term_OEA)
            else:
                contract.term = term_OEA_v2
                contract.term_detail = TermDetail.objects.get(title='1', term=term_OEA_v2)
        else:
            contract.term = term_dict[contract.contract_type.code]
            contract.term_detail = TermDetail.objects.get(title='1', term=term_dict[contract.contract_type.code])
        contract.save(update_fields=['term', 'term_detail'])


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0046_add_company'),
    ]

    operations = [
        migrations.RunPython(
            add_terms,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            set_term,
            reverse_code=migrations.RunPython.noop
        ),
    ]
