# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-10-14 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_set_contract_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='company_code',
            field=models.CharField(blank=True, help_text='기관코드', max_length=10, null=True),
        )
    ]
