# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-10-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0048_add_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='completed_at',
            field=models.DateTimeField(default=None, help_text='이전 완료일', null=True),
        )
    ]
