# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-10-26 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_contract_status(apps, schema_editor):
    ContractStatus = apps.get_model('contracts', 'contractstatus')

    ContractStatus.objects.create(category='Default', code=0, type='canceled', name='해지됨')
    ContractStatus.objects.create(category='Default', code=1, type='normal', name='정상 유지')
    ContractStatus.objects.create(category='Firmbanking', code=2, type='fee_st_reg', name='펌뱅킹 등록 중')
    ContractStatus.objects.create(category='Firmbanking', code=20, type='fee_st_reg_f1', name='펌뱅킹 등록 실패')
    ContractStatus.objects.create(category='Firmbanking', code=21, type='fee_st_reg_s', name='펌뱅킹 등록 완료')
    ContractStatus.objects.create(category='Account', code=22, type='account_sell_reg', name='해지 매도 진행 중')
    ContractStatus.objects.create(category='Account', code=23, type='account_sell_f1', name='해지 매도 실패')
    ContractStatus.objects.create(category='Account', code=24, type='account_sell_s', name='해지 매도 완료')
    ContractStatus.objects.create(category='Account', code=25, type='account_exchange_reg', name='환전 진행 중')
    ContractStatus.objects.create(category='Account', code=26, type='account_exchange_f1', name='환전 실패')
    ContractStatus.objects.create(category='Account', code=27, type='account_exchange_s', name='환전 완료')
    ContractStatus.objects.create(category='Withdraw', code=3, type='fee_st_withdraw', name='출금이체 진행 중')
    ContractStatus.objects.create(category='Withdraw', code=30, type='fee_st_withdraw_f1', name='출금이체 실패')
    ContractStatus.objects.create(category='Withdraw', code=31, type='fee_st_withdraw_s', name='출금이체 완료')
    ContractStatus.objects.create(category='Vendor', code=4, type='vendor_wait_cancel', name='협력사 해지 대기')
    ContractStatus.objects.create(category='Vendor', code=40, type='vendor_wait_account_id_card', name='협력사 계좌개설 신분증 대기')
    ContractStatus.objects.create(category='Vendor', code=41, type='vendor_wait_account', name='협력사 계좌개설 대기')
    ContractStatus.objects.create(category='Vendor', code=42, type='vendor_wait_order_proxy', name='주문대리인 등록 대기')
    ContractStatus.objects.create(category='Vendor', code=43, type='vendor_auth_fail', name='인증토큰 발급 실패')
    ContractStatus.objects.create(category='Vendor', code=44, type='vendor_customer_id_fail', name='증권사 식별정보 조회 실패')
    ContractStatus.objects.create(category='Vendor', code=45, type='vendor_upload_doc_fail', name='전자문서 전달 실패')
    ContractStatus.objects.create(category='Vendor', code=46, type='vendor_order_proxy_fail', name='주문대리인 등록 실패')
    ContractStatus.objects.create(category='Vendor', code=47, type='vendor_auth_fail_on_cancel', name='주문대리인 해지중 토큰발급 실패')
    ContractStatus.objects.create(category='Vendor', code=48, type='vendor_order_proxy_cancel', name='주문대리인 해지 대기')
    ContractStatus.objects.create(category='Vendor', code=49, type='vendor_order_proxy_cancel_fail', name='주문대리인 해지 실패')
    ContractStatus.objects.create(category='VendorContract', code=50, type='vendor_contract_advisory_wait', name='투자자문계약 등록 대기')
    ContractStatus.objects.create(category='VendorContract', code=51, type='vendor_contract_advisory_fail', name='투자자문계약 등록 실패')
    ContractStatus.objects.create(category='VendorContract', code=52, type='vendor_contract_quit_advisory_wait', name='투자자문계약 해지 대기')
    ContractStatus.objects.create(category='VendorContract', code=53, type='vendor_contract_quit_advisory_fail', name='투자자문계약 해지 실패')
    ContractStatus.objects.create(category='VendorContract', code=54, type='vendor_contract_transaction_limit_wait', name='임의거래 제한 대기')
    ContractStatus.objects.create(category='VendorContract', code=55, type='fractional_share_trading_waiting', name='소수점 매매 신청 대기')
    ContractStatus.objects.create(category='VendorContract', code=56, type='fractional_share_trading_success', name='소수점 매매 신청 완료')
    ContractStatus.objects.create(category='VendorContract', code=57, type='KRW_margin_apply_wait', name='원화증거금 신청 대기')
    ContractStatus.objects.create(category='VendorContract', code=58, type='KRW_margin_apply_success', name='원화증거금 신청 완료')
    ContractStatus.objects.create(category='BankingPlus', code=6, type='bp_fee_st_reg', name='뱅킹플러스 등록 중')
    ContractStatus.objects.create(category='BankingPlus', code=60, type='bp_fee_st_reg_fail', name='뱅킹플러스 등록 실패')
    ContractStatus.objects.create(category='BankingPlus', code=61, type='bp_fee_st_reg_success', name='뱅킹플러스 등록 완료')


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0049_change_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('category', models.CharField(default='Default', help_text='계약 상태 카테고리', max_length=40)),
                ('code', models.IntegerField(default=41, help_text='계약 상태 코드', primary_key=True, serialize=False)),
                ('type', models.CharField(default='vendor_wait_account', help_text='계약 상태 타입', max_length=40, unique=True)),
                ('name', models.CharField(default='협력사 계좌개설 대기', help_text='계약 상태명', max_length=40)),
            ],
        ),
        migrations.RunPython(
            migrate_contract_status,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(db_column='contract_status', help_text='계약 상태', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.ContractStatus'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='vendor',
            field=models.CharField(blank=True, help_text='상대 기관 및 지점명', max_length=100, null=True),
        ),
    ]
