# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-11-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_alter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='fixed_risk_type',
            field=models.BooleanField(default=False, help_text='위험성향 변경 가능 유무'),
        ),
    ]
