# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-05-26 16:51
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('tendencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='auth_type',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default='password',
                                                 help_text='투자성향 인증수단', max_length=100, no_check_for_status=True,
                                                 null=True),
        ),
    ]
