# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180323_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='vendor status'),
        ),
    ]
