# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:16
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_ci(apps, schema_editor):
    Contract = apps.get_model('contracts', 'contract')

    for contract in Contract.objects.all():
        try:
            contract.user.profile.ci = contract.ci
            contract.user.profile.save(update_fields=['ci'])
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_expiringtoken'),
        ('contracts', '0027_auto_20190319_1752')
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ci',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
        migrations.RunPython(
            migrate_ci,
            reverse_code=migrations.RunPython.noop
        ),
    ]
