# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import hashlib
import fernet_fields.fields


def set_encrypted_ci(apps, schema_editor):
    Profile = apps.get_model('users', 'profile')

    for profile in Profile.objects.filter(ci__isnull=False):
        profile.encrypted_ci = profile.ci
        profile.ci_hash = hashlib.sha256(profile.ci.encode('utf-8')).hexdigest()
        profile.save()


def set_decrypted_ci(apps, schema_editor):
    Profile = apps.get_model('users', 'profile')

    for profile in Profile.objects.filter(encrypted_ci__isnull=False):
        profile.ci = profile.encrypted_ci
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_auto_20191029_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_ci',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='고유식별번호', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ci_hash',
            field=models.CharField(blank=True, help_text='고유 식별번호 Hash값', max_length=64, null=True),
        ),
        migrations.RunPython(
            set_encrypted_ci,
            reverse_code=set_decrypted_ci
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ci',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='encrypted_ci',
            new_name='ci',
        ),
    ]
