# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-18 04:30
from __future__ import unicode_literals

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_encrypted_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTendency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('result', common.models.ListField(help_text='응답 결과')),
                ('forwarded_at', models.DateTimeField(blank=True, help_text='전달 일시', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='증권사', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_tendencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='ci_hash',
            field=models.CharField(blank=True, editable=False, help_text='고유 식별번호 Hash값', max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vendortendency',
            unique_together=set([('user', 'vendor')]),
        ),
    ]
