# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-04 16:16
from __future__ import unicode_literals

import api.bases.users.models
import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201111_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tendency_response',
            field=common.models.ListField(blank=True, help_text='투자성향 응답결과', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=api.bases.users.models.generate_referral_code, editable=False, help_text='추천인 코드', max_length=10),
        ),
    ]
