# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-06-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211205_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='자원 고유 ID', primary_key=True, serialize=False, unique=True)),
                ('file', models.ImageField(blank=True, height_field='height', help_text='이미지', null=True, upload_to='avatars', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, help_text='이미지 넓이', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='이미지 높이', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar', to='users.Image'),
        ),
    ]
