# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-07-04 06:15
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_type',
            field=models.IntegerField(blank=True, help_text='개인 성향', null=True),
        )
    ]
