# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-08-06 14:09
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_personal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='탈퇴일', null=True),
        )
    ]
