# Generated by Django 3.0.3 on 2021-05-04 06:15

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_portfolio_id'),
        ('orders', '0003_ordersetting_min_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trd_date', models.CharField(help_text='거래일자', max_length=8)),
                ('ord_no', models.IntegerField(help_text='거래일련번호')),
                ('quantity',
                 models.DecimalField(blank=True, decimal_places=4, help_text='거래수량', max_digits=30, null=True)),
                ('deposit_amt', models.IntegerField(blank=True, help_text='예수금잔고', null=True)),
                ('commission', models.IntegerField(blank=True, help_text='국내수수료', null=True)),
                ('in_come_tax', models.IntegerField(blank=True, help_text='소득세', null=True)),
                ('currency_name', models.CharField(blank=True, help_text='통화구분명', max_length=40, null=True)),
                ('pre_p_deposit', models.IntegerField(blank=True, help_text='결제선납입금액', null=True)),
                ('ex_deposit', models.FloatField(blank=True, help_text='외화예수금잔액', null=True)),
                ('j_name', models.CharField(blank=True, help_text='적요명', max_length=35, null=True)),
                ('settled_amt', models.IntegerField(blank=True, help_text='원화정산금액', null=True)),
                (
                'trd_p', models.DecimalField(blank=True, decimal_places=4, help_text='결제단가', max_digits=16, null=True)),
                ('trd_tax',
                 models.DecimalField(blank=True, decimal_places=4, help_text='제세금', max_digits=30, null=True)),
                ('reside_tax', models.IntegerField(help_text='주민세')),
                ('perfor_qty',
                 models.DecimalField(blank=True, decimal_places=4, help_text='유가증권변제수량', max_digits=30, null=True)),
                ('ex_chg_rate', models.FloatField(blank=True, help_text='환율', max_length=11, null=True)),
                ('pre_pay_repay', models.IntegerField(help_text='결제선납입금액변제')),
                ('stock_name', models.CharField(blank=True, help_text='종목명', max_length=50, null=True)),
                ('trd_amt',
                 models.DecimalField(blank=True, decimal_places=4, help_text='거래금액', max_digits=30, null=True)),
                ('agr_tax', models.IntegerField(blank=True, help_text='농특세', null=True)),
                ('unpaid_repay', models.IntegerField(blank=True, help_text='미수변제금액', null=True)),
                ('etc_repay', models.IntegerField(blank=True, help_text='기타대여금변제금액', null=True)),
                ('stock_qtry',
                 models.DecimalField(blank=True, decimal_places=4, help_text='유가증권잔고수량', max_digits=30, null=True)),
                ('for_comm_r', models.FloatField(blank=True, help_text='국외수수료', null=True)),
                ('for_amt_r', models.FloatField(blank=True, help_text='외화정산금액', null=True)),
                ('st_stock_code', models.CharField(blank=True, help_text='표준종목코드', max_length=12, null=True)),
                ('for_amt', models.IntegerField(blank=True, help_text='외화예수금', null=True)),
                ('j_code', models.CharField(blank=True, help_text='적요유형코드', max_length=3, null=True)),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'unique_together': {('account_alias', 'trd_date', 'ord_no')},
            },
        ),
    ]
