# Generated by Django 3.0.3 on 2021-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='risk_type',
            field=models.IntegerField(blank=True,
                                      choices=[(0, '초저위험'), (1, '저위험'), (2, '중위험'), (3, '고위험'), (4, '초고위험')],
                                      help_text='투자성향', null=True),
        ),
    ]
