# Generated by Django 3.0.3 on 2021-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_remove_account_portfolio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='strategy_code',
            field=models.IntegerField(default=0, help_text='전략 구분'),
        ),
    ]
