# Generated by Django 3.0.3 on 2021-08-04 01:55

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_settlement_sumup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('code', models.CharField(help_text='ISIN 코드', max_length=12)),
                ('shares', models.IntegerField(help_text='보유좌수')),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'unique_together': {('account_alias', 'created_at', 'code')},
            },
        ),
    ]
