# Generated by Django 3.0.3 on 2022-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_update_settlement'),
    ]
    operations = [
        migrations.AddField(
            model_name='settlement',
            name='settled_amt',
            field=models.BigIntegerField(help_text='당일 결제 대금(KRW, 세전)', null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settled_ask_amt',
            field=models.BigIntegerField(help_text='당일 매도 결제 대금(KRW, 세전)', null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settled_bid_amt',
            field=models.BigIntegerField(help_text='당일 매수 결제 대금(KRW, 세전)', null=True),
        ),
    ]
