# Generated by Django 3.0.3 on 2021-08-04 00:33

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('currency_code', models.CharField(help_text='외화코드(ISO4217)', max_length=3)),
                ('base_date', models.DateField(help_text='기준일')),
                ('open', models.DecimalField(decimal_places=4, help_text='오픈(매매기준율)', max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, help_text='종가', max_digits=15, null=True)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'unique_together': {('currency_code', 'base_date')},
            },
        ),
    ]
