# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-06-25 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tendencies', '0003_set_auth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='auth_type',
            field=model_utils.fields.StatusField(blank=True, choices=[(0, 'dummy')], default=30, help_text='투자성향 인증수단', max_length=100, no_check_for_status=True, null=True),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='end',
            field=models.IntegerField(default=0, help_text='범위 종료값'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='start',
            field=models.IntegerField(default=0, help_text='범위 시작값'),
        ),
    ]
