# Generated by Django 3.0.3 on 2020-12-16 10:37

import common.models
from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("managements", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queue",
            old_name="portfolio",
            new_name="portfolio_id",
        ),
        migrations.AddField(
            model_name="queue",
            name="order_basket",
            field=common.models.JSONField(
                blank=True,
                default="",
                editable=False,
                help_text="OrderBasket",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="mode",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                default="bid",
                help_text="주문 종류(sell: 매도청산, bid: 매수, ask: 매도)",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
