# Generated by Django 3.0.3 on 2021-08-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managements", "0004_auto_20210609_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="account_alias",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="계좌번호 별칭(INDEX)",
                max_length=128,
            ),
        ),
    ]
