# Generated by Django 3.0.3 on 2023-01-11 08:32

from django.db import migrations, models


def set_default_vendor_code(apps, schema_editor):
    Queue = apps.get_model('managements', 'queue')
    Queue.objects.all().update(vendor_code="kb")


class Migration(migrations.Migration):
    dependencies = [
        ('managements', '0005_auto_20210820_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='vendor_code',
            field=models.CharField(help_text='증권사구분', max_length=8, null=True),
        ),
        migrations.RunPython(
            set_default_vendor_code,
            reverse_code=migrations.RunPython.noop
        )
    ]
