# Generated by Django 3.0.3 on 2020-12-09 05:16

import django.utils.timezone
import fernet_fields.fields
import model_utils.fields
from django.db import migrations, models

import api.bases.accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0001_initial_order_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('account_alias',
                 models.CharField(default=api.bases.accounts.models.create_account_alias, editable=False,
                                  help_text='계좌번호 별칭(INDEX)', max_length=128, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(help_text='증권사구분', max_length=8)),
                ('account_number', fernet_fields.fields.EncryptedCharField(help_text='계좌번호(암호화필수)', max_length=128)),
                ('account_type',
                 models.CharField(choices=[('kr_fund', '국내 펀드'), ('kr_etf', '국내 ETF'), ('etf', '해외 ETF')],
                                  help_text='자산 구분(kr_fund: 국내 펀드, kr_etf: 국내 ETF, etf: 해외 ETF)', max_length=8)),
                ('status', models.IntegerField(
                    choices=[(0, '해지됨'), (1, '정상 유지'), (22, '해지 매도 진행 중'), (23, '해지 매도 실패'), (24, '해지 매도 완료'),
                             (25, '환전 진행 중'), (26, '환전 실패'), (27, '환전 완료'), (3, '운용 중지')], default=1,
                    help_text='계약 상태')),
                ('portfolio_id', models.BigIntegerField(blank=True, help_text='현재 운영 포트폴리오 ID', null=True)),
                ('deleted_at',
                 models.DateTimeField(blank=True, default=None, editable=False, help_text='삭제 요청 일자', null=True)),
                ('order_setting', models.ForeignKey(blank=True, help_text='주문 전략 설정', null=True,
                                                    on_delete=django.db.models.deletion.SET_NULL,
                                                    to='orders.OrderSetting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISIN 코드', max_length=12)),
                ('shares', models.IntegerField(help_text='좌수')),
                ('buy_price', models.IntegerField(help_text='매수금(KRW)')),
                ('balance', models.IntegerField(help_text='평가금(KRW)')),
                ('buy_price_usd', models.FloatField(help_text='매수금(USD)')),
                ('balance_usd', models.FloatField(help_text='평가금(USD)')),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'unique_together': {('account_alias', 'code', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base', models.IntegerField(help_text='투자원금(KRW)')),
                ('deposit', models.IntegerField(help_text='예수금(KRW)')),
                ('balance', models.IntegerField(help_text='평가금(KRW)')),
                ('prev_deposit', models.IntegerField(help_text='전일자 예수금(KRW)')),
                ('base_usd', models.FloatField(help_text='투자원금(USD)')),
                ('deposit_usd', models.FloatField(help_text='예수금(USD)')),
                ('balance_usd', models.FloatField(help_text='평가금(USD)')),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'unique_together': {('account_alias', 'created_at')},
            },
        ),
    ]
