# Generated by Django 3.0.3 on 2021-09-03 03:05

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumup',
            name='amount_func_type',
            field=models.CharField(blank=True,
                                   choices=[('INPUT', '원화 입금'), ('OUTPUT', '원화 출금'), ('OUTPUT_USD', '외화 출금'),
                                            ('IMPORT', '입고'), ('EXPORT', '출고'), ('DIVIDEND_INPUT', '배당금 입금'),
                                            ('DIVIDEND_OUTPUT', '배당금 출금'), ('OVERSEA_TAX', '해외 수수료'),
                                            ('OVERSEA_TAX_REFUND', '해외 수수료 반환')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sumup',
            name='trade_type',
            field=models.CharField(blank=True,
                                   choices=[('INPUT', '원화 입금'), ('OUTPUT', '원화 출금'), ('OUTPUT_USD', '외화 출금'),
                                            ('IMPORT', '입고'), ('EXPORT', '출고'), ('DIVIDEND_INPUT', '배당금 입금'),
                                            ('DIVIDEND_OUTPUT', '배당금 출금'), ('OVERSEA_TAX', '해외 수수료'),
                                            ('OVERSEA_TAX_REFUND', '해외 수수료 반환'), ('BID', '매수'), ('ASK', '매도'),
                                            ('SETTLEMENT_IN', '정산(입금)'), ('SETTLEMENT_OUT', '정산(출금)'),
                                            ('EXCHANGE', '환전'), ('INTEREST_DEPOSIT', '이자 입금')], max_length=30,
                                   null=True),
        ),
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('base', models.BigIntegerField(default=0, help_text='투자원금')),
                ('deposit', models.BigIntegerField(default=0, help_text='투자원금')),
                ('for_deposit',
                 models.DecimalField(decimal_places=4, default=0, help_text='외화 예수금 잔고(USD)', max_digits=15)),
                ('unsettled_for_amt',
                 models.DecimalField(decimal_places=4, default=0, help_text='외화 예수금 잔고(USD)', max_digits=15)),
                ('balance_usd',
                 models.DecimalField(decimal_places=4, default=0, help_text='외화 예수금 잔고(USD)', max_digits=15)),
                ('balance', models.BigIntegerField(default=0, help_text='투자원금')),
                ('liquidity', models.BigIntegerField(default=0, help_text='투자원금')),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='환율', max_digits=9)),
                ('profit_loss', models.BigIntegerField(default=0, help_text='평가손익')),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
