# Generated by Django 3.0.3 on 2021-09-15 09:03

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_add_daily_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   help_text='생성일')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          help_text='수정일')),
                ('input_amt', models.BigIntegerField(default=0, help_text='입금액')),
                ('output_amt', models.BigIntegerField(default=0, help_text='출금액')),
                ('input_usd_amt', models.BigIntegerField(default=0, help_text='외화입금액(원화환산)')),
                ('output_usd_amt', models.BigIntegerField(default=0, help_text='외화출금액(원화환산)')),
                ('import_amt', models.DecimalField(decimal_places=4, default=0, help_text='입고계', max_digits=15)),
                ('export_amt', models.DecimalField(decimal_places=4, default=0, help_text='출고계', max_digits=15)),
                ('dividend_input_amt',
                 models.DecimalField(decimal_places=4, default=0, help_text='배당금(세전)', max_digits=15)),
                ('dividend_output_amt',
                 models.DecimalField(decimal_places=4, default=0, help_text='배당금 출금(세전)', max_digits=15)),
                ('oversea_tax_amt', models.DecimalField(decimal_places=4, default=0, help_text='해외수수료', max_digits=15)),
                ('oversea_tax_refund_amt',
                 models.DecimalField(decimal_places=4, default=0, help_text='해외수수료 반환금', max_digits=15)),
                ('account_alias', models.ForeignKey(help_text='계좌번호 별칭', on_delete=django.db.models.deletion.CASCADE,
                                                    to='accounts.Account')),
            ],
            options={
                'unique_together': {('account_alias', 'created_at')},
            },
        ),
    ]
