# Generated by Django 3.0.3 on 2021-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_amounthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='unsettled_for_amt',
        ),
        migrations.AddField(
            model_name='settlement',
            name='acc_unsettled_for_amt',
            field=models.DecimalField(decimal_places=4, default=0, help_text='외화 미결제대금 잔고(USD, 세전)', max_digits=15),
        ),
        migrations.AddField(
            model_name='settlement',
            name='executed_for_ask_amt',
            field=models.DecimalField(decimal_places=4, default=0, help_text='당일 외화 매도 체결 대금(USD, 세전)', max_digits=15),
        ),
        migrations.AddField(
            model_name='settlement',
            name='executed_for_bid_amt',
            field=models.DecimalField(decimal_places=4, default=0, help_text='당일 외화 매수 체결 대금(USD, 세전)', max_digits=15),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settled_for_ask_amt',
            field=models.DecimalField(decimal_places=4, help_text='당일 매도 결제 대금(USD, 세전)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settled_for_bid_amt',
            field=models.DecimalField(decimal_places=4, help_text='당일 매수 결제 대금(USD, 세전)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sumup',
            name='amount_func_type',
            field=models.CharField(blank=True, choices=[('INPUT', '원화 입금'), ('OUTPUT', '원화 출금'), ('INPUT_USD', '외화 입금'),
                                                        ('OUTPUT_USD', '외화 출금'), ('IMPORT', '입고'), ('EXPORT', '출고'),
                                                        ('DIVIDEND_INPUT', '배당금 입금'), ('DIVIDEND_OUTPUT', '배당금 출금'),
                                                        ('OVERSEA_TAX', '해외 수수료'), ('OVERSEA_TAX_REFUND', '해외 수수료 반환')],
                                   max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sumup',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('INPUT', '원화 입금'), ('OUTPUT', '원화 출금'), ('INPUT_USD', '외화 입금'),
                                                        ('OUTPUT_USD', '외화 출금'), ('IMPORT', '입고'), ('EXPORT', '출고'),
                                                        ('DIVIDEND_INPUT', '배당금 입금'), ('DIVIDEND_OUTPUT', '배당금 출금'),
                                                        ('OVERSEA_TAX', '해외 수수료'), ('OVERSEA_TAX_REFUND', '해외 수수료 반환'),
                                                        ('BID', '매수'), ('ASK', '매도'), ('SETTLEMENT_IN', '정산(입금)'),
                                                        ('SETTLEMENT_OUT', '정산(출금)'), ('EXCHANGE', '환전'),
                                                        ('INTEREST_DEPOSIT', '이자 입금')], max_length=30, null=True),
        ),
    ]
