# Generated by Django 3.0.3 on 2022-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner_type',
            field=models.CharField(choices=[('corporate', '법인'), ('personal', '개인')], default='personal', help_text='소유 구분(corporate: 법인, personal: 개인)', max_length=12),
        ),
        migrations.AddField(
            model_name='account',
            name='pension_base_diff',
            field=models.IntegerField(default=0, help_text='계좌 연금 이전 시 원금과 평가금 차액'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(0, '종합위탁계좌'), ('cma', [(1, '환매조건부 채권'), (11, '단기금융펀드'), (12, '랩어카운트')]), ('pension', [(2, '연금 저축'), (21, '연금 IRP')])], default=0, help_text='계좌 구분'),
        ),
    ]
