# Generated by Django 3.0.3 on 2023-01-04 07:39

import api.bases.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_update_amount_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='acc_unsettled_for_amt',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='executed_for_ask_amt',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='executed_for_bid_amt',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_alias',
            field=models.CharField(default=api.bases.accounts.models.create_account_alias, help_text='계좌번호 별칭(INDEX)', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner_type',
            field=models.CharField(choices=[('personal', '개인'), ('corporate', '법인')], default='personal', help_text='소유 구분(personal: 개인, corporate: 법인)', max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, '해지됨'), (1, '정상 유지'), (22, '해지 매도 진행 중'), (23, '해지 매도 실패'), (24, '해지 매도 완료'), (25, '환전 진행 중'), (26, '환전 실패'), (27, '환전 완료'), ('suspension', [(3, '운용 중지'), (30, '이상 계좌 중지'), (31, '미지원 종목 보유 운용 중지'), (32, '최소 원금 위반 중지'), (33, '임의 거래 중지'), (34, '투자 성향 안정형 운용 중지')])], default=1, help_text='계약 상태'),
        ),
        migrations.AlterField(
            model_name='amounthistory',
            name='export_amt',
            field=models.DecimalField(decimal_places=6, default=0, help_text='출고계', max_digits=30),
        ),
        migrations.AlterField(
            model_name='amounthistory',
            name='import_amt',
            field=models.DecimalField(decimal_places=6, default=0, help_text='입고계', max_digits=30),
        ),
        migrations.AlterField(
            model_name='amounthistory',
            name='stock_export_amt',
            field=models.DecimalField(decimal_places=6, default=0, help_text='출고 총계', max_digits=30),
        ),
        migrations.AlterField(
            model_name='amounthistory',
            name='stock_import_amt',
            field=models.DecimalField(decimal_places=6, default=0, help_text='입고 총계', max_digits=30),
        ),
        migrations.AlterField(
            model_name='amounthistory',
            name='stock_transfer_amt',
            field=models.DecimalField(decimal_places=6, default=0, help_text='입출고 총계', max_digits=30),
        ),
        migrations.AlterField(
            model_name='assetdetail',
            name='shares',
            field=models.DecimalField(decimal_places=6, help_text='좌수', max_digits=30),
        ),
        migrations.AlterField(
            model_name='execution',
            name='exec_qty',
            field=models.DecimalField(decimal_places=6, help_text='체결수량', max_digits=30),
        ),
        migrations.AlterField(
            model_name='execution',
            name='ord_qty',
            field=models.DecimalField(decimal_places=6, help_text='주문수량', max_digits=30),
        ),
        migrations.AlterField(
            model_name='execution',
            name='unexec_qty',
            field=models.DecimalField(decimal_places=6, help_text='미체결수량', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='shares',
            field=models.DecimalField(decimal_places=6, help_text='보유좌수', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='export_amt',
            field=models.DecimalField(decimal_places=6, default=0, help_text='출고계', max_digits=30),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='import_amt',
            field=models.DecimalField(decimal_places=6, default=0, help_text='입고계', max_digits=30),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='거래수량', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock_qtry',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='유가증권잔고수량', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trd_p',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='결제단가', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trd_tax',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='제세금', max_digits=30, null=True),
        ),
    ]
