# Generated by Django 3.0.3 on 2020-12-09 07:02

import common.models
import common.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "account_alias",
                    models.CharField(
                        editable=False, help_text="계좌번호 별칭(INDEX)", max_length=128
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "지연중"),
                            (2, "실패"),
                            (3, "대기중"),
                            (4, "진행중"),
                            (5, "완료됨"),
                            (6, "취소됨"),
                            (7, "건너뜀"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "management_at",
                    models.DateTimeField(
                        default=common.utils.get_local_today, editable=False
                    ),
                ),
                (
                    "mode",
                    model_utils.fields.StatusField(
                        choices=[
                            ("new_order", "신규"),
                            ("sell", "매도"),
                            ("buy", "매수"),
                            ("rebalancing", "리밸런싱"),
                        ],
                        default="new_order",
                        help_text="주문 종류(new_order: 신규, sell: 매도, buy: 매수, rebalancing: 리밸런싱)",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("portfolio", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="예외사항 정보", max_length=128, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("00", "주문 모니터링"), ("01", "오류"), ("02", "이상탐지")],
                        default="00",
                        help_text="리포트 종류(00: 주문 모니터링, 01: 오류, 02: 이상탐지)",
                        max_length=4,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", help_text="주문 리포트", max_length=200),
                ),
                ("body", models.TextField(default="", help_text="본문")),
                ("config", common.models.JSONField(default={}, help_text="사용한 설정 값")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_report",
                        to="managements.Queue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="ISIN 코드", max_length=12, null=True
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            ("Bid", [(10, "매수 신청"), (11, "매수 정정"), (12, "매수 취소")]),
                            ("Ask", [(20, "매도 신청"), (21, "매도 정정"), (22, "매도 취소")]),
                        ],
                        help_text="주문 구분",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "지연중"),
                            (2, "실패"),
                            (3, "대기중"),
                            (4, "진행중"),
                            (5, "완료됨"),
                            (6, "취소됨"),
                            (7, "건너뜀"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "order_no",
                    models.IntegerField(blank=True, help_text="주문번호", null=True),
                ),
                (
                    "order_price",
                    models.FloatField(blank=True, help_text="주문금액", null=True),
                ),
                (
                    "market_price",
                    models.FloatField(blank=True, help_text="시장가격(15분 지연)", null=True),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(blank=True, help_text="주문 집행 일시", null=True),
                ),
                (
                    "concluded_at",
                    models.DateTimeField(blank=True, help_text="체결 확인 일시", null=True),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, help_text="국가 코드", max_length=2, null=True
                    ),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(
                        blank=True, default=0, help_text="좌수", null=True
                    ),
                ),
                (
                    "error_msg",
                    models.CharField(
                        blank=True, help_text="에러 사유", max_length=128, null=True
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_logs",
                        to="managements.Queue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
