# Generated by Django 3.0.3 on 2021-06-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managements", "0003_auto_20210528_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorset",
            name="error_id",
            field=models.IntegerField(
                choices=[
                    (1001, "투자금미달"),
                    (1002, "미지원 종목 보유"),
                    (1003, "고객 임의 거래 시도"),
                    (1004, "해지매도 실패"),
                    (1005, "비밀번호 사고 오류"),
                    (2001, "MP sum 1 오류"),
                    (2002, "MP 일임 서비스 금지 종목 포함"),
                    (2004, "API 작동 오류"),
                    (2005, "emphasis_ordersetting 확인"),
                    (2006, "portfolio_type확인"),
                ],
                help_text="에러 종류",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
