# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 03:03
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
from django.contrib.auth import get_user_model

from api.bases.notifications.choices import ProtocolTypes


def set_default_subscribe(apps, schema_editor):
    Subscribe = apps.get_model('notifications', 'subscribe')
    Topic = apps.get_model('notifications', 'topic')

    for user in get_user_model().objects.all().only('id'):
        sub_instance, _ = Subscribe.objects.get_or_create(
            user_id=user.id,
            type=ProtocolTypes.Sms.value
        )
        sub_instance.topics.add(Topic.objects.get(name='notification'))


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0002_auto_20180115_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='protocol',
            field=models.CharField(blank=True, choices=[('2', 'Email'), ('3', 'Push'), ('1', 'Sms')], help_text='전송 방법',
                                   max_length=1, null=True),
        ),
        migrations.RunPython(
            set_default_subscribe,
            reverse_code=migrations.RunPython.noop
        )
    ]
