# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_subscribe_news_topic(apps, schema_editor):
    Subscribe = apps.get_model('notifications', 'subscribe')
    Topic = apps.get_model('notifications', 'topic')
    User = apps.get_model('users', 'user')

    news_topic = Topic.objects.get(name='news')

    for user in User.objects.all():
        for protocol in ["1", "3"]:
            sub_instance, _ = Subscribe.objects.get_or_create(
                user=user,
                type=protocol
            )
            sub_instance.topics.add(news_topic)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_expiringtoken'),
        ('notifications', '0005_auto_20180904_0909'),
    ]

    operations = [
        migrations.RunPython(
            migrate_subscribe_news_topic,
            reverse_code=migrations.RunPython.noop
        ),
    ]
