# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-16 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='동의 일시')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(help_text='동의 타입 코드', max_length=60, unique=True)),
                ('name', models.CharField(help_text='동의 타입명', max_length=60)),
                ('description', models.TextField(blank=True, help_text='동의 타입 설명', null=True)),
                ('is_required', models.BooleanField(default=False, help_text='동의 필수 여부 true:필수 false:선택')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='동의 타입 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='동의 타입 수정일')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together=set([('id', 'code')]),
        ),
        migrations.AddField(
            model_name='agreement',
            name='type',
            field=models.ForeignKey(help_text='동의 타입', on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='agreements.Type'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='user',
            field=models.ForeignKey(help_text='유저', on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together=set([('type', 'user')]),
        ),
    ]
