# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='exp_days',
            field=models.PositiveIntegerField(default=0, help_text='동의 유효 일수'),
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together=set([]),
        ),
    ]
