# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
