# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tendency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviters', to=settings.AUTH_USER_MODEL)),
                ('joiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joiners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([('inviter', 'joiner')]),
        ),
    ]
