# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 01:19
from __future__ import unicode_literals

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190320_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_carrier',
            field=models.CharField(blank=True, choices=[('01', 'SKT'), ('02', 'KT'), ('03', 'LG U+'), ('알뜰폰', [('04', 'SKT'), ('05', 'KT'), ('06', 'LG U+')])], help_text='휴대폰 통신사', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='주소', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='생년월일', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ci',
            field=models.CharField(blank=True, help_text='고유식별번호', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='config',
            field=common.models.JSONField(blank=True, default={}, help_text='기타 설정', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('내국인', [(1, '남(1)'), (2, '여(2)'), (3, '남(3)'), (4, '여(4)'), (9, '남(9)'), (0, '여(10)')]), ('외국인', [(5, '남(5)'), (6, '여(6)'), (7, '남(7)'), (8, '여(8)')])], help_text='성별', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text='이름', max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='휴대폰 번호', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='risk_type',
            field=models.IntegerField(blank=True, help_text='위험 성향', null=True),
        ),
    ]
