# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190403_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProperty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vendor_props', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('investment', '증권사'), ('partner', '협력사')], max_length=12)),
                ('company_name', models.CharField(help_text='회사명', max_length=30)),
                ('code', models.CharField(help_text='관리코드', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'vendor properties',
                'db_table': 'users_vendor_property',
            },
        ),
    ]
