# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 14:59
from __future__ import unicode_literals

import api.bases.users.models
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


def set_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'site')
    User = apps.get_model('users', 'user')

    try:
        if not Site.objects.exists():
            Site(pk=getattr(settings, 'SITE_ID', 1), domain='127.0.0.1', name='127.0.0.1').save()
        else:
            Site.objects \
                .filter(domain='example.com', name='example.com') \
                .update(domain='127.0.0.1', name='127.0.0.1')

        default_site = Site.objects.first()

        for user in User.objects.only('site'):
            user.site = default_site
            user.save()

            if user.socialaccount_set.exists():
                socialaccount = user.socialaccount_set.get()
                socialaccount.uid = f'{socialaccount.uid}-{default_site.id}'
                socialaccount.save()
    except Exception as e:
        print(e)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('users', '0011_vendorproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, default=api.bases.users.models.get_default_site, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('email', 'site')]),
        ),
        migrations.RunPython(
            set_default_site,
            reverse_code=migrations.RunPython.noop
        )
    ]
