# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 06:48
from __future__ import unicode_literals

from django.db import migrations, models
from django.template.loader import get_template
import django.db.models.deletion


def set_default_site_settings(apps, schema_editor):
    Site = apps.get_model('sites', 'site')
    Setting = apps.get_model('users', 'sitesettings')

    t = get_template('member_join.html')

    for site in Site.objects.all():
        Setting.objects.create(wc_template=t.template.source, site=site)


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('users', '0012_auto_20190718_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_wc_email', models.BooleanField(default=True, help_text='회원가입시 이메일 발송여부')),
                ('wc_template', models.TextField(blank=True, help_text='회원가입 이메일 템플릿', null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings',
                                              to='sites.Site', to_field='domain')),
            ],
        ),
        migrations.RunPython(
            set_default_site_settings,
            reverse_code=migrations.RunPython.noop
        )
    ]
