# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-29 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tendency',
            options={'verbose_name_plural': 'Tendencies'},
        ),
        migrations.AddField(
            model_name='profile',
            name='funnels',
            field=models.CharField(blank=True, help_text='유입경로', max_length=128, null=True),
        ),
    ]
