# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_update_tendency_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproperty',
            name='restrict_end',
            field=models.DateTimeField(blank=True, help_text='장애처리 종료시간', null=True),
        ),
        migrations.AddField(
            model_name='vendorproperty',
            name='restrict_start',
            field=models.DateTimeField(blank=True, help_text='장애처리 시작시간', null=True),
        ),
    ]
